### ISSUE TITLE
PPTP doesn't work

### ISSUE THREAD

**Issue by taobaodog** [sabaitechnology/SabaiOpen#162]
Tue Feb  2 17:21:59 2016 kern.info kernel: [  586.024494] pptp-vpn: renamed from ppp0
Tue Feb  2 17:21:59 2016 daemon.info pppd[5792]: Using interface pptp-vpn
Tue Feb  2 17:21:59 2016 daemon.notice pppd[5792]: Connect: pptp-vpn <--> pptp (str-atl101.reliablehosting.com)
Tue Feb  2 17:21:59 2016 daemon.notice privoxy[6079]: Started successfully
Tue Feb  2 17:22:00 2016 daemon.warn pppd[5839]: Non-zero Async Control Character Maps are not supported!
Tue Feb  2 17:22:00 2016 daemon.info pppd[5792]: EAP: unknown authentication type 26; Naking
Tue Feb  2 17:22:00 2016 daemon.err pppd[5792]: EAP: peer reports authentication failure
Tue Feb  2 17:22:00 2016 daemon.warn pppd[5839]: Non-zero Async Control Character Maps are not supported!
Tue Feb  2 17:22:00 2016 daemon.notice pppd[5792]: Connection terminated.
Tue Feb  2 17:22:00 2016 daemon.info pppd[5792]: Exit.
Tue Feb  2 17:22:00 2016 daemon.notice netifd: Interface 'vpn' is now down
Tue Feb  2 17:22:00 2016 daemon.notice netifd: Interface 'vpn' is setting up now
Tue Feb  2 17:22:00 2016 daemon.err uhttpd[1802]: ifconfig: pptp-vpn: error fetching interface information: Device not found
Tue Feb  2 17:22:00 2016 daemon.info pppd[6158]: Plugin pptp.so loaded.
Tue Feb  2 17:22:00 2016 daemon.info pppd[6158]: PPTP plugin version 1.00
Tue Feb  2 17:22:00 2016 daemon.notice pppd[6158]: pppd 2.4.7 started by root, uid 0

**Comment by wmhaynes** [comment]
I have made a fix.  The issue is with newer windows servers "refuse-eap"
should be passed to avoid these issues.

Sincerely,

*William Haynes*
Chief Executive Officer / Founder
Sabai Technology <http://www.sabaitechnology.com/> | RouterSource.com
<http://routersource.com/>
+1
864.962.4072 | +1 864.962.4073

[image: Sabai Technology] <http://www.sabaitechnology.com>  [image: William
Haynes] <https://www.linkedin.com/in/sabaitechnology>  [image: Twitter]
<https://twitter.com/sabaitechnology>  [image: Facebook]
<https://www.facebook.com/sabairouters>
