### ISSUE TITLE
Forwarding rules incorrect and keep adding more

### ISSUE THREAD

**Issue by wmhaynes** [sabaitechnology/SabaiOpen#92]
Forwarding not allowing traffic from eth0.  Also  each time vpn is started, a new forwarding rule is added and old ones are not deleted.

Warning: Section @forwarding[0] refers to not existing zone 'lan'
Warning: Section @forwarding[1] refers to not existing zone 'lan'
Warning: Section @forwarding[2] refers to not existing zone 'lan'
Warning: Section @forwarding[3] refers to not existing zone 'lan'
Warning: Section @forwarding[4] refers to not existing zone 'lan'
Warning: Section @forwarding[5] refers to not existing zone 'lan'

Next time VPN is started
Warning: Section 'vpn' cannot resolve device of network 'vpn'
Warning: Section @forwarding[0] refers to not existing zone 'lan'
Warning: Section @forwarding[1] refers to not existing zone 'lan'
Warning: Section @forwarding[2] refers to not existing zone 'lan'
Warning: Section @forwarding[3] refers to not existing zone 'lan'
Warning: Section @forwarding[4] refers to not existing zone 'lan'
Warning: Section @forwarding[5] refers to not existing zone 'lan'
Warning: Section @forwarding[6] refers to not existing zone 'lan'

A new forwarding rule is added each time.  This affects both vpna and router versions of SabaiOpen.

**Comment by taobaodog** [comment]
Thu Nov 19 11:37:28 2015 user.emerg syslog: uci: Entry not found
Thu Nov 19 11:37:28 2015 user.emerg syslog: Error: an inet prefix is expected rather than ".0/24".
Thu Nov 19 11:37:28 2015 user.emerg syslog: Error: an inet prefix is expected rather than ".0/24".
Thu Nov 19 11:37:28 2015 user.emerg syslog: Error: an inet prefix is expected rather than ".0/24".
Thu Nov 19 11:37:28 2015 user.emerg syslog: Error: an inet address is expected rather than ".2"
